"use client"

import { useState } from "react"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Search, ExternalLink, Clock, Calendar, Github, Sparkles, Zap, ArrowRight } from "lucide-react"
import { repoDocs } from "./data"
import { Link } from "react-router-dom"

export default function ExploreDocs() {
    const [searchQuery, setSearchQuery] = useState("")
    const [hoveredCard, setHoveredCard] = useState<string | null>(null)

    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 relative overflow-hidden">
            {/* Animated background elements */}
            <div className="absolute inset-0 overflow-hidden">
                <div className="absolute -top-40 -right-40 w-80 h-80 bg-purple-500 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-pulse"></div>
                <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-pink-500 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-pulse delay-1000"></div>
                <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-80 h-80 bg-blue-500 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-pulse delay-500"></div>
            </div>

            {/* Subtle grid pattern overlay */}
            <div
                className="absolute inset-0 pointer-events-none opacity-10"
                style={{
                    backgroundImage:
                        "url(\"data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fillRule='evenodd'%3E%3Cg fill='%239C92AC' fillOpacity='0.4'%3E%3Ccircle cx='30' cy='30' r='1'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E\")",
                    backgroundSize: "60px 60px",
                }}
            />

            <section className="relative py-20 px-4 max-w-7xl mx-auto">
                {/* Floating header */}
                <div className="text-center mb-16 relative">
                    <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/10 backdrop-blur-md border border-white/20 mb-6 text-white/80 text-sm font-medium">
                        <Sparkles className="w-4 h-4" />
                        AI-Powered Documentation
                    </div>

                    <h1 className="text-6xl md:text-7xl font-black mb-6 relative">
                        <span className="bg-gradient-to-r from-white via-purple-200 to-pink-200 bg-clip-text text-transparent">
                            CodeNexAI
                        </span>
                        <br />
                        <span className="bg-gradient-to-r from-purple-400 via-pink-400 to-blue-400 bg-clip-text text-transparent">
                            Docs Library
                        </span>
                    </h1>

                    <p className="text-xl text-white/70 max-w-2xl mx-auto leading-relaxed">
                        Curated GitHub repository documentation generated by{" "}
                        <span className="text-purple-300 font-semibold">CodeNexAI</span>
                    </p>
                </div>

                {/* Floating search bar */}
                {/* <div className="flex justify-center mb-16">
                    <div className="relative w-full max-w-2xl">
                        <div className="absolute inset-0 bg-gradient-to-r from-purple-500/20 to-pink-500/20 rounded-2xl blur-xl"></div>
                        <div className="relative bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl p-1">
                            <div className="flex items-center gap-3 px-6 py-4">
                                <Search className="w-5 h-5 text-white/60" />
                                <Input
                                    placeholder="Search repos, tech stacks, or tags..."
                                    value={searchQuery}
                                    onChange={(e) => setSearchQuery(e.target.value)}
                                    className="bg-transparent border-none text-white placeholder:text-white/50 text-lg focus-visible:ring-0 focus-visible:ring-offset-0"
                                />
                                <Button
                                    size="sm"
                                    className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 border-none text-white font-medium px-6"
                                >
                                    Search
                                </Button>
                            </div>
                        </div>
                    </div>
                </div> */}

                {/* Cards grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-20">
                    {repoDocs.map((repo, index) => (
                        <div
                            key={repo.id}
                            className="group relative"
                            onMouseEnter={() => setHoveredCard(repo.id)}
                            onMouseLeave={() => setHoveredCard(null)}
                            style={{
                                animationDelay: `${index * 150}ms`,
                            }}
                        >
                            {/* Glow effect */}
                            <div className="absolute -inset-0.5 bg-gradient-to-r from-purple-500 to-pink-500 rounded-3xl blur opacity-0 group-hover:opacity-30 transition duration-500"></div>

                            <Card className="relative bg-white/10 backdrop-blur-md border border-white/20 rounded-3xl overflow-hidden transition-all duration-500 group-hover:scale-105 group-hover:bg-white/15">
                                <CardContent className="p-8">
                                    {/* Header */}
                                    <div className="flex items-start gap-4 mb-6">
                                        <div className="relative">
                                            <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-purple-500/20 to-pink-500/20 backdrop-blur-sm border border-white/20 flex items-center justify-center overflow-hidden">
                                                <img
                                                    //src={repo.logo || "/placeholder.svg"}
                                                    alt={repo.name}
                                                    className="w-10 h-10 object-contain"
                                                />
                                            </div>
                                            <div className="absolute -top-1 -right-1 w-6 h-6 bg-gradient-to-r from-green-400 to-emerald-400 rounded-full flex items-center justify-center">
                                                <Zap className="w-3 h-3 text-white" />
                                            </div>
                                        </div>

                                        <div className="flex-1">
                                            <h3 className="text-2xl font-bold text-white mb-1">{repo.name}</h3>
                                            <div className="flex items-center gap-2 text-purple-300 text-sm font-medium">
                                                <Sparkles className="w-3 h-3" />
                                                Generated by CodeNexAI
                                            </div>
                                        </div>
                                    </div>

                                    {/* Description */}
                                    <p className="text-white/70 mb-6 leading-relaxed">{repo.description}</p>

                                    {/* Meta info */}
                                    <div className="space-y-3 mb-6">
                                        <div className="flex items-center gap-2 text-white/60 text-sm">
                                            <Clock className="w-4 h-4" />
                                            <span>
                                                Generated in <span className="text-purple-300 font-medium">{repo.generationTime}s</span>
                                            </span>
                                        </div>
                                        <div className="flex items-center gap-2 text-white/60 text-sm">
                                            <Calendar className="w-4 h-4" />
                                            <span>
                                                Created on <span className="text-purple-300 font-medium">{repo.createdOn}</span>
                                            </span>
                                        </div>
                                        <div className="flex items-center gap-2 text-white/60 text-sm">
                                            <Github className="w-4 h-4" />
                                            <a
                                                href={repo.sourceUrl}
                                                target="_blank"
                                                rel="noopener noreferrer"
                                                className="text-purple-300 hover:text-purple-200 transition-colors font-medium hover:underline"
                                            >
                                                {repo.sourceName}
                                            </a>
                                        </div>
                                    </div>

                                    {/* Tags */}
                                    <div className="flex flex-wrap gap-2 mb-8">
                                        {repo.tags.map((tag, tagIndex) => (
                                            <Badge
                                                key={tagIndex}
                                                className="bg-white/10 text-white border-white/20 hover:bg-white/20 transition-colors px-3 py-1 text-xs font-medium"
                                            >
                                                {tag}
                                            </Badge>
                                        ))}
                                    </div>

                                    {/* Action button */}
                                    <Button
                                        asChild
                                        className="w-full bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white font-semibold py-3 rounded-xl transition-all duration-300 group/btn"
                                    >
                                        <a
                                            href={`/docs/${repo.id}`}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="flex items-center justify-center gap-2"
                                        >
                                            <ExternalLink className="w-4 h-4" />
                                            View Documentation
                                            <ArrowRight className="w-4 h-4 transition-transform group-hover/btn:translate-x-1" />
                                        </a>
                                    </Button>
                                </CardContent>
                            </Card>
                        </div>
                    ))}
                </div>

                {/* CTA Section */}
                <div className="relative">
                    <div className="absolute inset-0 bg-gradient-to-r from-purple-500/20 via-pink-500/20 to-blue-500/20 rounded-3xl blur-2xl"></div>
                    <div className="relative bg-gradient-to-r from-purple-500/10 via-pink-500/10 to-blue-500/10 backdrop-blur-md border border-white/20 rounded-3xl p-12 text-center">
                        <div className="max-w-3xl mx-auto">
                            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/10 backdrop-blur-md border border-white/20 mb-6 text-white/80 text-sm font-medium">
                                <Zap className="w-4 h-4" />
                                Ready to Get Started?
                            </div>

                            <h2 className="text-4xl md:text-5xl font-bold mb-4">
                                <span className="bg-gradient-to-r from-white to-purple-200 bg-clip-text text-transparent">
                                    Want Docs for Your Repo?
                                </span>
                            </h2>

                            <p className="text-xl text-white/70 mb-8 leading-relaxed">
                                We'll generate comprehensive, intelligent documentation in seconds using our advanced AI technology.
                            </p>

                            <div className="flex flex-col sm:flex-row gap-4 justify-center">
                                <a
                                    href="https://codenexai.com"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    <Button
                                        size="lg"
                                        className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white font-semibold px-8 py-4 rounded-xl transition-all duration-300 group"
                                    >
                                        <Sparkles className="w-5 h-5 mr-2" />
                                        Try CodeNexAI Today
                                        <ArrowRight className="w-5 h-5 ml-2 transition-transform group-hover:translate-x-1" />
                                    </Button>
                                </a>

                                {/* <Button
                                    variant="outline"
                                    size="lg"
                                    className="border-white/20 text-white hover:bg-white/10 backdrop-blur-md px-8 py-4 rounded-xl transition-all duration-300 bg-transparent"
                                >
                                    View Examples
                                </Button> */}
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    )
}
